Update trufflehog-scan.yml

diff --git a/.github/workflows/trufflehog-scan.yml b/.github/workflows/trufflehog-scan.yml
--- a/.github/workflows/trufflehog-scan.yml
+++ b/.github/workflows/trufflehog-scan.yml
@@ -35,7 +35,7 @@ jobs:
     - name: Run TruffleHog Scan
       run: |
         echo "Running TruffleHog scan..."
-        trufflehog --json . > trufflehog_report.json || { echo 'TruffleHog scan failed'; exit 1; }
+        trufflehog --json https://github.com/Twist-hash/VulnerableApp.git > trufflehog_report.json || { echo 'TruffleHog scan failed'; exit 1; }
 
     - name: Display TruffleHog Report
       run: |
